# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "./download_strategies/custom_download_strategy"
class Goyaml < Formula
  desc "Utility for performing simple operations on a YAML file."
  homepage "https://github.com/theochva/goyaml"
  version "0.3.1"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/theochva/goyaml/releases/download/v0.3.1/goyaml_0.3.1_darwin_x86_64.tar.gz", :using => CustomGitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "f18dacfebb665f47ff9bc9e09700f6fc8bf5297f402305b3132eacf0cf436c3b"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/theochva/goyaml/releases/download/v0.3.1/goyaml_0.3.1_linux_x86_64.tar.gz", :using => CustomGitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "b96091e8b6e2129b7f31dffc9718bede434b89a20c9a4cab2f4b3dc9882954f5"
  end

  def install
    bin.install "goyaml"
  end

  test do
    system "#{bin}/goyaml --version"
  end
end
